modLoader="javafml"
loaderVersion="[45,)"
issueTrackerURL="https://github.com/MattCzyr/Notes/issues"
license="CC BY-NC-SA 4.0"
[[mods]]
    modId="notes"
    version="${file.jarVersion}"
    displayName="Notes"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/notes"
    authors="ChaosTheDude"
    description='''
    Clientside in-game notepad.
    '''

[[dependencies.notes]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.notes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"
